name: Build Website

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pelican pyyaml beautifulsoup4 ghp-import
        git clone --depth=1 --single-branch --branch main https://github.com/rlanzafame/pelican-alchemy.git
        git clone --depth=1 https://github.com/getpelican/pelican-plugins.git
    - name: Build the website
      run: |
        pelican -D -v --fatal errors -s publishconf.py -o output
    - name: Deploy the website
      if: ${{ github.event_name == 'push' }}
      run: |
        git fetch origin
        git checkout deploy
        git pull origin deploy
        git config --global user.name "Github Actions"
        git config --global user.email rlanzafame@users.noreply.github.com
        git remote add deploy "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/rlanzafame/rlanzafame.github.io.git"
        ghp-import -r deploy -b main -m "Updated via Github Actions [skip ci]" -p output